version: "3.3"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    networks:
      - wpsite
  
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=project
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_server
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql_server
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - wpsite
networks:
  wpsite:
    
